<?php

declare(strict_types=1);

namespace Promopult\TikTokMarketingApi\Appendix;

/**
 * @psalm-suppress UnusedClass
 */
final class AreaCode
{
    public static function getAreaCodes(): array
    {
        return [
            ['Andorra', 'AD'],
            ['United Arab Emirates', 'AE'],
            ['Afghanistan', 'AF'],
            ['Antigua and Barbuda', 'AG'],
            ['Albania', 'AL'],
            ['Armenia', 'AM'],
            ['Angola', 'AO'],
            ['Argentina', 'AR'],
            ['Austria', 'AT'],
            ['Australia', 'AU'],
            ['Azerbaijan', 'AZ'],
            ['Bosnia & Herzegovina', 'BA'],
            ['Barbados', 'BB'],
            ['Bangladesh', 'BD'],
            ['Belgium', 'BE'],
            ['Burkina Faso', 'BF'],
            ['Bulgaria', 'BG'],
            ['Bahrain', 'BH'],
            ['Burundi', 'BI'],
            ['Benin', 'BJ'],
            ['Brunei', 'BN'],
            ['Bolivia', 'BO'],
            ['Brazil', 'BR'],
            ['Commonwealth of the Bahamas', 'BS'],
            ['Bhutan', 'BT'],
            ['Botswana', 'BW'],
            ['Belarus', 'BY'],
            ['Belize', 'BZ'],
            ['Canada', 'CA'],
            ['Switzerland', 'CH'],
            ['Cote D\'Ivoire', 'CI'],
            ['Chile', 'CL'],
            ['Cameroon', 'CM'],
            ['China', 'CN'],
            ['Colombia', 'CO'],
            ['Costa Rica', 'CR'],
            ['Cape Verde', 'CV'],
            ['Cyprus', 'CY'],
            ['Czech Republic', 'CZ'],
            ['Germany', 'DE'],
            ['Djibouti', 'DJ'],
            ['Denmark', 'DK'],
            ['Dominica', 'DM'],
            ['Dominican Republic', 'DO'],
            ['Algeria', 'DZ'],
            ['Ecuador', 'EC'],
            ['Estonia', 'EE'],
            ['Egypt', 'EG'],
            ['Eritrea', 'ER'],
            ['Spain', 'ES'],
            ['Ethiopia', 'ET'],
            ['Finland', 'FI'],
            ['Fiji', 'FJ'],
            ['Micronesia', 'FM'],
            ['France', 'FR'],
            ['Gabon', 'GA'],
            ['United Kingdom', 'GB'],
            ['Grenada', 'GD'],
            ['Georgia', 'GE'],
            ['Ghana', 'GH'],
            ['Gibraltar', 'GI'],
            ['Gambia', 'GM'],
            ['Guinea', 'GN'],
            ['Equatorial Guinea', 'GQ'],
            ['Greece', 'GR'],
            ['Guatemala', 'GT'],
            ['Guinea-Bissau', 'GW'],
            ['Guyana', 'GY'],
            ['Hong Kong', 'HK'],
            ['Honduras', 'HN'],
            ['Croatia', 'HR'],
            ['Haiti', 'HT'],
            ['Hungary', 'HU'],
            ['Indonesia', 'ID'],
            ['Ireland', 'IE'],
            ['Israel', 'IL'],
            ['India', 'IN'],
            ['Iraq', 'IQ'],
            ['Iceland', 'IS'],
            ['Italy', 'IT'],
            ['Jamaica', 'JM'],
            ['Jordan', 'JO'],
            ['Japan', 'JP'],
            ['Kenya', 'KE'],
            ['Kyrgyzstan', 'KG'],
            ['Cambodia', 'KH'],
            ['Kiribati', 'KI'],
            ['Comoros', 'KM'],
            ['Saint Christopher and Nevis', 'KN'],
            ['Korea, South', 'KR'],
            ['Kuwait', 'KW'],
            ['Cayman Islands', 'KY'],
            ['Kazakhstan', 'KZ'],
            ['Laos', 'LA'],
            ['Lebanon', 'LB'],
            ['Saint Lucia', 'LC'],
            ['Liechtenstein', 'LI'],
            ['Sri Lanka', 'LK'],
            ['Liberia', 'LR'],
            ['Lesotho', 'LS'],
            ['Lithuania', 'LT'],
            ['Luxembourg', 'LU'],
            ['Latvia', 'LV'],
            ['Libya', 'LY'],
            ['Morocco', 'MA'],
            ['Monaco', 'MC'],
            ['Moldova', 'MD'],
            ['Montenegro', 'ME'],
            ['Madagascar', 'MG'],
            ['Marshall Islands', 'MH'],
            ['Macedonia', 'MK'],
            ['Mali', 'ML'],
            ['Myanmar', 'MM'],
            ['Mongolia', 'MN'],
            ['Macau', 'MO'],
            ['Mauritania', 'MR'],
            ['Malta', 'MT'],
            ['Mauritius', 'MU'],
            ['Maldives', 'MV'],
            ['Malawi', 'MW'],
            ['Mexico', 'MX'],
            ['Malaysia', 'MY'],
            ['Mozambique', 'MZ'],
            ['Namibia', 'NA'],
            ['Niger', 'NE'],
            ['Nigeria', 'NG'],
            ['Nicaragua', 'NI'],
            ['Netherlands', 'NL'],
            ['Norway', 'NO'],
            ['Nepal', 'NP'],
            ['Nauru', 'NR'],
            ['New Zealand', 'NZ'],
            ['Oman', 'OM'],
            ['Panama', 'PA'],
            ['Peru', 'PE'],
            ['Papua New Guinea', 'PG'],
            ['Philippines', 'PH'],
            ['Pakistan', 'PK'],
            ['Poland', 'PL'],
            ['Puerto Rico', 'PR'],
            ['Palestine', 'PS'],
            ['Portugal', 'PT'],
            ['Palau', 'PW'],
            ['Paraguay', 'PY'],
            ['Qatar', 'QA'],
            ['Romania', 'RO'],
            ['Serbia', 'RS'],
            ['Russia', 'RU'],
            ['Rwanda', 'RW'],
            ['Saudi Arabia', 'SA'],
            ['Solomon Islands', 'SB'],
            ['Seychelles', 'SC'],
            ['Sweden', 'SE'],
            ['Singapore', 'SG'],
            ['Slovenia', 'SI'],
            ['Slovakia', 'SK'],
            ['Sierra Leone', 'SL'],
            ['San Marino', 'SM'],
            ['Senegal', 'SN'],
            ['Somali', 'SO'],
            ['Suriname', 'SR'],
            ['Sao Tomé and Príncipe', 'ST'],
            ['El Salvador', 'SV'],
            ['Swaziland', 'SZ'],
            ['Chad', 'TD'],
            ['Togo', 'TG'],
            ['Thailand', 'TH'],
            ['Tajikistan', 'TJ'],
            ['Timor-Leste', 'TL'],
            ['Turkmenistan', 'TM'],
            ['Tunisia', 'TN'],
            ['Tonga', 'TO'],
            ['Turkey', 'TR'],
            ['Trinidad and Tobago', 'TT'],
            ['Tuvalu', 'TV'],
            ['Taiwan', 'TW'],
            ['Tanzania', 'TZ'],
            ['Ukraine', 'UA'],
            ['Uganda', 'UG'],
            ['United States', 'US'],
            ['Uruguay', 'UY'],
            ['Uzbekistan', 'UZ'],
            ['Vatican City', 'VA'],
            ['Saint Vincent and The Grenadines', 'VC'],
            ['Venezuela', 'VE'],
            ['British Virgin Islands', 'VG'],
            ['Vietnam', 'VN'],
            ['Vanuatu', 'VU'],
            ['Samoa', 'WS'],
            ['Yemen', 'YE'],
            ['South Africa', 'ZA'],
            ['Zambia', 'ZM'],
            ['Zimbabwe', 'ZW'],
        ];
    }
}
