<?php

declare(strict_types=1);

namespace Promopult\TikTokMarketingApi\Appendix;

final class Industry
{
    public static function getIndustries(): array
    {
        return [
            [290101, "3C and Peripheral Products", "Including companies that produce，R&D， and sell 3C electronic products， such as digital 3C， game machines， routers， household cloud servers， balance vehicles， electric skateboards， and unmanned aerial vehicles (UAV)， as well as office equipment like projectors， printers， etc"],
            [290102, "Electric Appliances", "Including home appliances and commercial appliances， Kitchen appliances， appliances used in the bathroom， all kinds of household health care equipment."],
            [290103, "Others", "Items not included into the categories above."],
            [290104, "Mobile Phone", "Refers to enterprises that produce， develop， and sell mobile phones. e.g apple iphone"],
            [290105, "Mobile Phone Accessories", "Refers to enterprises that produce， develop， and sell mobile phone accessories. Mobile phone accessories include data lines， mobile phone brackets (including on-board brackets)， mobile power (charger)， mobile phone parts， mobile phone shells， mobile phone batteries， etc."],
            [290106, "Computer", "Refers to enterprises that produce， develop and sell computers. Computers include desktops， laptops， tablets， etc. e.g apple Macbook， Levovo， Dell"],
            [290107, "Computer Accessories", "Refers to enterprises that produce， develop， and sell computer accessories including data lines， keyboards， power (charger)， etc."],
            [290108, "3C Products and Electric Appliance E-Commerce", "E-commerce platform for the sale of 3C products and electric appliance products to households and individuals"],
            [290109, "3C Products and Off-line Retail of Electric Appliances", "Physical stores selling 3C and electric appliance products， new retail is classified as off-line"],
            [290201, "Health and Personal Care", "Personal care and cleaning products， home care products"],
            [290202, "Ordinary Comestics", "Daily chemical industrial products (excluding sunscreen) produced by applying， spraying or other similar methods on any parts of the human body surface for the purpose of cleaning， eliminating bad odors， skin care， and decoration."],
            [290203, "High-end Comestics or Luxury Comestics", "Including high-end skin care products， cosmetics， perfume， etc. (4 times price higher than regular marketing price， and needs to have its owner brand)"],
            [290204, "Special Cosmetics", "Refers to the cosmetics used for sun block， hair care， hair dye， perm， unhairing， breast beauty， bodybuilding， deodorization， anti-freckle， weight loss."],
            [290205, "Tobacco", "Companies engaged in sales， wholesale， agency， etc. including electronic cigarette."],
            [290206, "Pet Supplies", "Pet food， cleaning products， daily necessities， excluding veterinary medicine"],
            [290207, "Mother and Baby Products", "Refers to professional health products particularly for pregnant women and babies aged 0-3 (children's clothing belongs to clothing accessories -- general clothing shoes and hats)"],
            [290208, "Others", "Items not included into the categories above."],
            [290209, "Adult Supplies", "Enterprises with adult sexual health products as their main products"],
            [290210, "Cosmetics and Daily Chemical E-Commerce", "E-commerce platform for selling cosmetics and daily chemical goods to families and individuals"],
            [290211, "Cosmetics and Daily Chemical Off-Line Retail", "Physical stores selling cosmetics and daily chemical goods. New retail is classified as offline"],
            [290212, "Maternal and Infant Products E-Commerce", "E-commerce platform for selling mother and infant products to families and individuals"],
            [290213, "Maternal and Infant Products Off-Line Retail", "Physical stores selling mother-and-child products， children's toys and other products"],
            [290214, "Tobacco and Alcohol E-Commerce", "E-commerce platform for families and individuals to sell tobacco and wine products"],
            [290215, "Tobacco and of Alcohol Off-Line Retail", "Physical stores selling tobacco， drinks and other products. New retail is classified as offline"],
            [290216, "Pet Supplies E-Commerce", "E-commerce platform for selling pet products and veterinary drugs to families and individuals"],
            [290217, "Pet Products Off-Line Retail", "Physical stores selling pets and pet products (excluding veterinary drugs)， New retail is classified as offline"],
            [290301, "Snacks", "Companies that provide processed food or snacks for people: might include salting， roasting， drying， cooking， or canning nuts; (2) processing grains or seeds into snacks; (3) manufacturing peanut butter; and (4) manufacturing potato chips， corn chips， popped popcorn， pretzels (except soft)， pork rinds， and similar snacks， etc."],
            [290302, "Beverage", "Companies providing soft drinks (non-dairy products)， tea， coffee， cereal， honey and other processed food (including milk tea)"],
            [290303, "Beer， Wine， and Liquor", "Companies engaged in wine production， sales， wholesale， agency， etc."],
            [290304, "Dairy Products & Dairy Drinks", "Dairy products: refers to products made of cow's milk， goat's milk or its processed products; Dairy drinks refer to products made from fresh milk or dairy products through fermentation or non-fermentation (excluding milk tea)."],
            [290305, "Food & Ingredients", "Companies that provide cheese， oil， seeds， soups， sauces， cereal， seasoning."],
            [290306, "Fresh Food", "Companies that provide vegetables， fruits， meat， eggs and other primary agricultural products for consumers."],
            [290307, "Meal replacement", "Companies that provide partial or full dietary supplements in the form of powders， bars， shakes， and porridge."],
            [290308, "Other Primary Farm Produce", "Unprocessed products of plant， animal husbandry and fishery except fresh food， grain， oil， rice， noodles and dairy products， such as medlar， ginseng， American ginseng， royal jelly， bird's nest stack."],
            [290309, "Dietary Supplements & Healthy Food", "Products (non-primary agricultural products) that can supplement nutrients the body needs， and do not have the function of adjuvant therapy， e.g. GNC."],
            [290310, "Others", "Items not included into the categories above."],
            [290311, "Food and Beverage (Non-Fresh) E-Commerce", "E-commerce platform for selling food and beverages (except fresh food) to families and individuals"],
            [290312, "Food and Beverage (Non-Fresh) Off-Line Retail", "Physical stores selling food and beverage (non-fresh) products， new retail is classified as offline"],
            [290313, "Fresh Products E-Commerce", "E-commerce platform for selling fresh food to families and individuals"],
            [290314, "Fresh Products Off-Line Retail", "Physical stores selling meat， poultry， eggs， fruits， vegetables and other fresh products， new retail is classified as offline"],
            [290401, "Ordinary Clothing & Shoes", "General men's wear， general women's wear， children's wear (over 3 years old)， home wear， underwear and special clothing (such as swimsuit， protection suit， excluding professional sportswear， etc.) and shoes， socks， hats， gloves， belts and other clothing accessories."],
            [290402, "Luxury Clothing & Shoes", "Including high-grade clothing (4 times price higher than regular marketing price， and needs to have its owner brand.)"],
            [290403, "Ordinary Glasses & Bags", "Including general glasses & bags"],
            [290404, "Luxury Glasses & Bags", "Including high-grade glasses & bags (4 times price higher than regular marketing price， and needs to have its owner brand)"],
            [290405, "Ordinary Watches", "Including general watches"],
            [290406, "Luxury Watches", "Including high-grade glasses & bags (4 times price higher than regular marketing price， and needs to have its owner brand.)"],
            [290407, "Ordinary Jewelries", "General jewelries"],
            [290408, "Luxury Jewelries", "High-grade jewelries (4 times price higher than regular marketing price， and needs to have its owner brand)"],
            [290409, "Others", "Items not included into the categories above."],
            [290410, "Clothing Accessories E-Commerce", "E-commerce platform for selling clothing and accessories to families and individuals"],
            [290411, "Clothing Accessories Off-Line Retail", "Physical stores selling clothing， accessories， bags and other products，New retail is classified as offline"],
            [290501, "Medical Institutions", "Mainly refers to hospitals and other health institutions (including veterinary) that provide various kinds of medical services， (medical license is required)， the ultimate goal is to cure diseases or improve health."],
            [290502, "Medical Devices", "Instruments， equipment， apparatus， in vitro diagnostic (IVD) reagents and calibrators， materials and other similar articles directly or indirectly used in the human body. They are classified into categories I， ii and iii."],
            [290503, "Peripheral Medical Services", "Mainly includes psychological counseling， genetic testing， overseas medical treatment， rehabilitation center and other peripheral medical services."],
            [290504, "Others", "Items not included into the categories above."],
            [290505, "Medicines", "This is more emphasis on over-the-counter drugs. All links belong to drugs， including drug sales， drug production and pharmaceutical research and development (excluding veterinary drugs)."],
            [290506, "Health Products", "Having a national blue hat， which has the commonality of general food， can regulate the functions of the human body， suitable for specific people to eat， but not for the purpose of treating diseases"],
            [290507, "Integrated Medical Service Platform", "Refers to a platform that provides comprehensive information on the medical industry and the transformation of online and offline transactions. Some platforms also have their own online malls selling medical-related goods."],
            [290508, "Veterinary Medicines", "A substance (including pharmaceutical feed additives) used to prevent， treat， diagnose animal diseases or purposefully regulate animal physiological functions."],
            [290509, "Online Pharmacies/Pharmaceutical E-Commerce", "Refers to the e-commerce platform selling drugs， health products， medical devices， etc.， also known as online pharmacies"],
            [290510, "Pharmacy/Pharmaceutical offline retail", "Physical stores selling drugs， health products， medical devices， etc.， also known as pharmacies， new retail is classified as offline. e.g CVS Health"],
            [290601, "Safety and Security Services", "Refers to companies engaged in security service， r&d， production， sales and maintenance of security equipment， including police equipment and security services， such as anti-theft， disaster prevention， radiation prevention， monitoring and life-saving， etc"],
            [290602, "Publishing", "Work related to books， newspapers， periodicals， audio-visual products， digital publishing (publishing services that disseminate digital content products through the Internet) and other work starting from editing， production to distribution."],
            [290603, "Packaging & Printing", "Use certain packaging materials according to certain commodity attributes and forms， and the decoration and beautification of the printing of commodities through the design and arrangement， as well as other packaging and printing activities"],
            [290604, "Agency Services", "Refers to organizations (except for overseas study and insurance intermediaries) between producers， business operators and consumers that are legally qualified to provide services to producers， business operators and consumers."],
            [290605, "Consulting Services", "Refers to the knowledge-based service industry that collects， processes， sorts out， analyzes and transmits all kinds of information through various information processing technologies， to provide customers with information products such as solutions， strategies， suggestions， plans or measures to solve problems"],
            [290606, "Advertising & PR services", "Refers to the paid publicity activities for customers in newspapers， periodicals， street signs， light boxes， shop windows， Internet， communication equipment， radio， film and television and other media."],
            [290607, "Commercial Performance & Exhibition", "It refers to performance and exhibition services， scientific and technological exhibition services， tourism exhibition services， sports exhibition services， cultural exhibition services and other services related to conferences and exhibitions， with the purpose to achieve commercial profits"],
            [290608, "Design", "Professional design services such as engineering design， software design， integrated circuit design， industrial design， etc."],
            [290609, "Accounting & Taxation", "Refers to services related to tax planning， tax accounting and tax declaration."],
            [290610, "Legal Services", "Refers to the litigation services and non-litigation services provided by law firms and lawyers， including litigation agency， legal consulting， commercial account management etc."],
            [290611, "HR services", "Including a variety of web platforms that provide job seeking information， business information， including headhunting services， job platform."],
            [290612, "OEM", "Companies that provide manufacturing and processing services， like Foxxcon"],
            [290613, "IT Security", "Compnies that provide the protection of computer systems from the theft of or damage to their hardware， software， or electronic data， as well as from the disruption or misdirection of the services they provide."],
            [290614, "Others", "Items not included into the categories above."],
            [290701, "Comprehensive Services and online platform. (No: Comprehensive Services)", "Organizations or platforms that provide a variety of services. Such as Craigslist.org"],
            [290702, "Convenience Service", "The professional institutions that provide home services for consumers， including daily life management services， unlocking， water and electricity maintenance， home appliance maintenance， watch maintenance， waste recycling， recharge， certificate handling， stamp engraving and pest control."],
            [290703, "Housekeeping Services", "To provide cleaning services， baby-sitting services， maternity services for families or individuals."],
            [290704, "Nursing Services", "Refers to the maternity hotels， postpartum care institutions， special care， senior apartments and other community non-medical institutions."],
            [290705, "Photography", "Refers professional organizations focusing on photography， including wedding photography， personalized photo， family photo， identification photo， etc"],
            [290706, "Beauty Service", "Organizations that provide beauty & hairdressing services， including barbershops， beauty salons， spas， massages， nail care， hair planting， tanning， tattoo， etc."],
            [290707, "Recycle Service", "Organizations or platforms that provide household goods and recycling services."],
            [290708, "Rental Service", "Refers to organizations or platforms that provide rental services (besides renting cars and renting a house) for clothing， furniture， electrical appliances， outdoor equipment， mechanical equipment and other durable consumer goods"],
            [290709, "Dating and Matching Services", "Refers to organizations or platforms that provide dating services， marriage-seeking services， and relationships maintaining services， etc. Such as Tinder or Tantan"],
            [290710, "Delivery Service", "Immediate delivery services related to daily life (including fruits， fresh food， catering， grocery， etc.) ， like UberEats."],
            [290711, "Immigration Services", "Refers to organizations providing immigration services， including investment immigration， housing immigration， passport immigration， etc"],
            [290712, "Utilities Service", "Companies that provide gas， electricity， water services"],
            [290713, "Others", "Items not included into the categories above."],
            [290714, "Emotional Counseling", "A psychological counselor helps to resolve various emotions and improve physical and mental health through conversations with visitors."],
            [290715, "Marriage Services", "Professional institutions providing services for couples' weddings (excluding hotels providing venue rental)"],
            [290716, "Funeral Services", "Services for the disposal of dead bodies， etc"],
            [290801, "Real Estate Developer", "Companies engaged in the development， sales and leasing of residential and commercial real estate both at home and abroad (including industrial parks)"],
            [290802, "Real Estate Agency", "The company or individual at home and abroad does not have the ownership of the house， and only acts as an agent or the supplier of the leased house to complete the transaction of the house， commercial real estate and leasing"],
            [290803, "Property Management Company", "A company or institution specializing in the professional management of permanent above-ground buildings， ancillary equipment， facilities and related sites around， to provide a comfortable living or working environment for owners and non-owners."],
            [290804, "Real Estate Sales Agency", "It mainly refers to the companies entrusted by real estate developers to provide integrated marketing programs and carry out real estate sales on their behalf."],
            [290805, "Apartment Rental", "Mainly refers to the buildings or communities that are for residential purposes"],
            [290806, "Others", "Items not included into the categories above."],
            [290807, "Real Estate Integrated Service Platform", "It not only provides real estate-related information， but also provides online and offline transaction information， which can go back down the line to participate in more trading links， such as Fangduo， etc."],
            [290901, "Home Decoration Materials", "Refers to companies that produce construction materials and main decoration materials， used in construction and design， including construction steel plate， heat insulation materials， concrete， floor， tiles， cabinets， doors， kitchen， sanitary ware， etc"],
            [290902, "Hardware & Electrical", "It refers to the hardware and electrical supplies used in production and operation， including all kinds of metal doors and windows， lamps and lanterns， plumbing pipes， etc"],
            [290903, "Decoration Design", "Refers to companies engaged in architectural design， decoration design， decoration， installation and related services， including home decoration， tooling and comprehensive decoration."],
            [290904, "Furniture", "Companies that customize， produce and sell furniture that are mainly used in the living room， bedroom， kitchen， dining room and office， (including the whole-house custom furniture and furniture sold separately)"],
            [290905, "Home Accessories", "Mainly including home txtiles， storage products， carpet fabrics and other home decorative accessories， including all kinds of household daily necessities."],
            [290906, "Others", "Items not included into the categories above."],
            [290907, "General Merchandise", "Refers to all kinds of daily necessities (pots and pans， storage articles， etc.) needed for home life， excluding home ornaments"],
            [290908, "Decoration Environment Governance", "Air treatment in office and home environments， such as formaldehyde removal"],
            [290909, "Decoration Auxiliary Materials", "Refers to the use of auxiliary materials in the production and management of building structures and decoration， such as waterproof paint， glass glue， paint， latex paint， kraft paper， wallpaper， etc."],
            [290910, "Construction Works", "Refers to an engineering entity formed through the construction of various types of housing buildings and their ancillary facilities and the installation of their supporting lines， pipelines and equipment."],
            [290911, "Home Building Materials Integrated Service Platform", "Refers to a platform that provides comprehensive information on home building materials and transforms online and offline transactions. Some platforms also have their own online shopping malls selling home building materials."],
            [290912, "Home Building Materials E-Commerce", "E-commerce platform for selling home building materials to families and individuals"],
            [290913, "Home Building Materials Off-Line Retail", "Physical stores selling home building materials， new retail is classified as offline"],
            [291001, "Early Childhood Education", "Mainly for pregnancy and preschool education， including fetal education， childhood education， nursery schools， etc."],
            [291002, "Primary & Secondary Education", "It covers all kinds of school education and tutoring training from primary school to senior high school， aiming at subject knowledge acquisition and performance improvement."],
            [291003, "College Education", "Junior college， undergraduate， graduate， MBA， EMBA and other academic education"],
            [291004, "Language Learning & Studying Abroad", "Companies that provide language training or consulting services of studying abroad"],
            [291005, "Interest & Hobby Training", "Including institutions engaged in art training， sports training and other interest-based training"],
            [291006, "Professionl technique training. (no: Profession education)", "Job-oriented or skills-oriented institutions that provide training， such as cooking and driving."],
            [291007, "Corporate and Quality Development", "Refers to quality development training institutions targeted for enterprises or individuals"],
            [291008, "Others", "Items not included into the categories above."],
            [291009, "Special Groups Education", "Special education and training for people with intellectual， perceptual or motor impairment， immigrants who do not know the national language or illiterate people in the country"],
            [291101, "Scenic Spots", "Refers to the operation of tourist attractions， cultural venues， tourist facilities， ticketing services of scenic spots， performance， and other related tourist attractions: scenic spots， parks， recreation areas， theme parks， etc"],
            [291102, "Accommodation", "Entity enterprises providing accommodation and conference rooms， such as hotels， guesthouses， home stay inns， youth hostels， etc"],
            [291103, "OTA(Online Travel Agent)", "Platforms that provide tourism services (including hotel booking， scenic spot ticket booking， air ticket booking， cruise line booking， etc.)， tourism products (group tour， customized tour， independent travel， etc.)， tourism information and other online booking service."],
            [291104, "Travel Agency", "Refers to travel agencies and travel service providers that mainly provide offline tourism， business conference and company conference services."],
            [291105, "Airline Company", "Companies or organizations providing air passenger services"],
            [291106, "Ground Passenger Transport", "Companies or organizations providing ground passenger services"],
            [291107, "Railway Passenger Transport", "Companies or organizations providing railway passenger services"],
            [291108, "Water Passenger Transport", "Companies providing water transport service， including cruise， yacht， etc."],
            [291109, "Ticket Agency", "Companies or organizations engaged in ticket agents such as air tickets， train tickets， ship tickets and bus tickets"],
            [291110, "City Trip", "Provide travel services (e.g.， didi， taxi， etc.) according to the schedule， and provide vehicles rental services (e.g.， Hertz， AVIS car rental etc.) on a fixed time basis."],
            [291111, "Others", "Items not included into the categories above."],
            [291201, "Government Affairs for Traveling(No: Government Affairs)", "Refers to government agencies and organizations in charge of culture and tourism"],
            [291202, "Nonprofit/NGO", "Refers to non-governmental and non-profit organizations， such as environmental organizations， public welfare organizations"],
            [291203, "Municipal Construction", "Municipal engineering， such as urban planning， urban landscape， road greening， tourism landscape， real estate landscape， municipal road construction， culture and education， health， sports， music and other public facilities construction， memorial building facilities construction."],
            [291204, "Religion", "Religious Institutions"],
            [291205, "Politics", "Institutions that are related to political compaign or affairs"],
            [291206, "Others", "Items not included into the categories above."],
            [291207, "Government， Science， Education， and Health", "Refers to government agencies and organizations in charge of science， education and public health"],
            [291208, "Government Environmental Safety", "Government agencies and organizations responsible for the environment and security"],
            [291301, "Casual & Intellective Games", "Candy crash， guessing games， puzzle games， etc"],
            [291302, "Card and Board Games", "Texas Pokers， Black Jack， Uno， etc."],
            [291303, "RPG (Role-playing Games)", "PG and other role-playing games， like Final Fantasy， Diablo， etc."],
            [291304, "Action & Shooting Games", "Fighting games， gunfire games， aircraft games， tank war games"],
            [291305, "Racing & Sports Games", "Boxing， sports， raching games"],
            [291306, "Simulation Games", "Dressing games， farm games， nurture games (idol， pet， etc.)， business management games."],
            [291307, "Strategy Games", "Aiming to win games. For example: Age of Empires， Starcraft"],
            [291308, "Multiplayer Online Games", "Including large-scale online multiplayer games， including moba (Glory of Kings， Onmyoji)， mmo (Warcraft， lol， Dota， etc.)"],
            [291309, "Others", "Items not included into the categories above."],
            [291310, "Parent-Children Games", "It is a game of entertainment between parents within the family and their children."],
            [291311, "Adventure Games", "Adventure games focus on plot and exploratory interactions such as exploring the unknown and solving puzzles. Adventure games also emphasize the excavation of story clues， which mainly test the players' observation and analysis."],
            [291401, "Comprehensive 2B E-commerce", "The website sell products involving multi-brand， multi-product， and multi-category"],
            [291402, "Vertical 2B E-commerce", "Having multi-brand， multi-product， multi-category website sales products (with price) for enterprises users."],
            [291403, "Comprehensive 2C E-commerce", "Having multi-brand， multi-product， multi-category website sales products (with price) for individuals and families. e.g: Amaozn， Ebay"],
            [291404, "Social E-commerce", "Using Internet social media to achieve one or more links in e-commerce， such as traffic acquisition， commodity promotion and trading， to produce an online business platform of indirect or direct trading behavior."],
            [291405, "Vertical 2C E-commerce", "Having multi-brand， multi-product， multi-category of website selling products (with price) for individuals and families."],
            [291406, "Comprehensive Offline Retail", "Mainly refers to offline transactions. The products sold involve multiple brands， multiple products and multiple categories， including shopping malls and supermarkets. New retail is categorized into offline transactions. e.g: Walmart"],
            [291407, "Vertical Offline Retail", "Mainly refers to offline transactions. Users need to go to real stores to complete physical transactions. Having multiple brands， multiple products and multiple categories， including shopping malls and supermarkets. New retail is categorized into offline transactions."],
            [291408, "Others", "Other retails that are not included into the categories above."],
            [291501, "Aircraft Manufacturer", "Including aircraft manufacturers， dealers and maintenance agencies"],
            [291502, "Shipbuilders", "Including ship manufacturers， dealers and maintenance agencies"],
            [291503, "Motorbike Manufacturer", "Including motorbike manufacturers， dealers and maintenance agencies"],
            [291504, "Non-motor Vehicle Manufacturer", "Including bicycles， tricycles， battery cars， single-person electric cars manufacturers， dealers and maintenance agencies"],
            [291505, "Functional Vehicles", "Including sprinklers， snack trucks， garbage trucks， tractors， ambulances and other functional vehicle manufacturers."],
            [291506, "Others", "Items not included into the categories above."],
            [291507, "Transportation Post-Market", "Refers to the peripheral service market of various means of transport， including cleaning， spare parts sales， beauty， maintenance testing， modification， etc."],
            [291601, "Household Vehicle Manufacturer", "Includes four wheeler vehicles manufacturers， Refers to the marketing department of the main engine plants， including brand department， media department， public relations department， marketing department， etc.， and the regional branches/sales regions under the main engine plants sales company."],
            [291602, "Automobile Dealers", "Mainly includes the automobile dealer and other channel distributers"],
            [291603, "Second-hand Automobile Business", "It mainly refers to the agencies or platforms that promote second-hand vehicles trading， namely the automobile e-commerce platform and the automobile offline second-hand trading market organizer."],
            [291604, "Automotive Sevice", "Refers to the automobile peripheral service market， including car cleaning， automobile spare parts sales， automobile beauty， automobile maintenance and testing， automobile quick repair chain service， automobile modification and so on"],
            [291605, "Others", "Items not included into the categories above."],
            [291606, "Automotive Integrated Service Platform", "Refers to provide not only car-related information， but also online and offline transaction information， can be diverted to the line to participate in more links， and may have their own e-commerce mall customers， such as Yi car， car home， and so on."],
            [291607, "New Car Off-Line Retail", "Offline places for the sale of multi-brand cars， including car fairs for the main purpose of sales， excluding car dealers， 4S stores"],
            [291608, "Motorbike Manufacturer", "Includes Two and Three wheeler vehicles manufacturers， Refers to the marketing department of the main engine plants， including brand department， media department， public relations department， marketing department， etc.， and the regional branches/sales regions under the main engine plants sales company."],
            [291609, "Commercial Vehicle Manufacturer", "Includes commercial vehicles manufacturers (both light and heavy)， Refers to the marketing department of the main engine plants， including brand department， media department， public relations department， marketing department， etc.， and the regional branches/sales regions under the main engine plants sales company."],
            [291701, "Crop Production", "Production activities related to rice， wheat， corn， beans， edible fungi， cotton， hemp， mulberry silk， ball plants， climbing plants， palm plants， lawn， fruit trees， green seedlings， tea， coffee beans， fruit， nuts， dried fruit， flowers and other crops"],
            [291702, "Forestry", "Production activities related to seedlings， potted plants， bonsai， wine grape planting， shrubs， bamboo and other crops."],
            [291703, "Aquaculture", "Aquatic production activities involved in freshwater products， seafood products (fish， shrimp， shellfish， algae， crabs， turtles， etc.)"],
            [291704, "Hunting", "The practice of killing or trapping animals， or pursuing or tracking them with the intent of doing so"],
            [291705, "Animal Production", "Production activities engaged in chickens， ducks， cattle， sheep， pigeons， deer， snakes， rabbits， swans， frogs， peacocks， yellow mealworms， ants， spiders， foxes， bees， yaks and other animals， as well as relevant activities such as fur acquisition， animal hair collection， and slaughtering."],
            [291706, "Agriculture & Forestry Service", "Seedlings culture， seed culture， seed production， food industry rice， rice seed， wheat seed crop planting， fine seed breeding and propagation， rice and wheat planting， cotton processing and circulation services and other production activities."],
            [291707, "Farm Produce Processing", "To produce and sell feed， feed additives， pet feed， aquatic feed， fish meal， fish feed， pig feed， poultry feed， edible bacteria， pharmaceutical bacteria， and rice processing and other agricultural products services， agricultural products processing and circulation"],
            [291708, "Chemical Fertilizers and Pesticides", "Enterprises engaged in the sales of chemical fertilizers and pesticides and the research and development of pesticide production. Pesticides mainly used to kill the harmful creatures (pests， acarus， nematodes， pathogenic bacteria， weeds and mice) and the chemical and biological drugs used to regulate plant growth."],
            [291709, "Others", "Items not included into the categories above."],
            [291801, "Chemical Products", "Any use of chemical methods to change the composition or structure of substances， or the synthesis of new substances， are chemical production technology， that is， chemical process， the resulting products are called chemicals or chemical products."],
            [291802, "Disinfection Products", "Including disinfectants， disinfectant instruments and sanitary products"],
            [291803, "Hazardous Chemicals", "Refers to the companies that produce， sell or process highly toxic chemicals or other chemicals that are toxic， corrosive， explosive， combustible or combustion-supporting in nature and harmful to human body， facilities and environment"],
            [291804, "Food Chemical Materials", "Refers to enterprises specializing in the production and processing of food or food additives (excluding planting enterprises， breeding enterprises and catering enterprises)"],
            [291805, "Others", "Chemical industry of farm produce， fermentation industry， biochemical industry， marine chemical industry， environmental protection chemical industry， chemical industry of pyrotechnic products， etc"],
            [291806, "Fuel Energy", "Enterprises engaged in finished oil， natural gas， coal mining and marketing."],
            [291807, "Electrical Energy", "Enterprises engaged in hydropower， thermal power and power sales (including charging piles)"],
            [291808, "New Energy", "Enterprises engaged in production and sales of solar power， wind power， nuclear power， tidal power."],
            [291809, "Mineral Resources", "Mining， processing， smelting， marketing of metals and minerals."],
            [291810, "Pollution Treatment", "Refers to treatment equipment and services of water pollution， air pollution， soil pollution， noise and waste， including environmentally friendly toilets， garbage treatment， water pollution treatment， soil pollution treatment， air pollution treatment， noise pollution treatment， disinfection and sterilization， environmental assessment， integrated pollution treatment， etc."],
            [291811, "Waste Recycle", "Chemical waste recovery， metal resources recovery， plastic and rubber recovery"],
            [291812, "Energy Conservation", "Refers to energy saving products and services， including water resources， electricity， petroleum， natural gas， coal， residual heat and steam， energy saving solutions and services， and comprehensive energy saving."],
            [291813, "Others", "Items not included into the categories above."],
            [291901, "Electronic Devices", "Refers to electronic components and devices， including basic logic gates， registers， decoders， shaping circuits， power management chips， relays， capacitors， resistors， connectors， potentiometers， insurance components， sensors， display devices， frequency converters， etc."],
            [291902, "Instrument and Apparatus", "It refers to the apparatus or devices used to test the energy and parameter status of the measured objects， including automatic instrument， optical instrument， composition analyzer， intelligent instrument， analytical instrument， industrial control equipment， measuring instrument， pedometer， etc."],
            [291903, "Electrical & Electronics", "Power equipment， power distribution and transmission equipment， lighting equipment， battery， electrical materials， power supply appliances， frequency converter， radiator， stair accessories， temperature controller， heating equipment， compressor， building electrical， high and low voltage appliances， motors， insulation products， steam turbine， water turbine， electrical equipment， insulation materials， charger"],
            [291904, "Electric Machinery", "Machinery that manufactures power generation equipment， transformers， high and low voltage switches， wires and cables， batteries， electronic products and other electrical equipment"],
            [291905, "Others", "Items not included into the categories above."],
            [292001, "General Mechanical Equipment", "Refers to general mechanical equipment， including refrigeration， drying equipment， pumps， boilers， testing machines， internal combustion engines， conveying and feeding equipment， fans， valves， gas compressors， water tanks and so on."],
            [292002, "Agricultural and Forestry Machinery", "Refers to machinery and equipment used in agriculture， forestry， animal husbandry and fishery， including soil tillage machinery， planting machinery， harvesting machinery， tractors， meat processing machinery， feed processing equipment， fishery machinery and forestry machinery."],
            [292003, "Mineral Machinery", "Refers to machinery and equipment used in oil， natural gas and mineral exploration as well as smelting and casting equipment."],
            [292004, "Construction Machinery", "Refers to construction machinery and brick and tile production machinery used in engineering construction. Including cranes， elevators and accessories， aerial work machinery， drilling machine， concrete machinery， road machinery， excavators， building materials production and processing machinery， brick machine， tile machine."],
            [292005, "Chemical Machinery", "Machinery used in the chemical industry. Including reaction equipment， filtration equipment， separation equipment， oil processing equipment， sterilization equipment."],
            [292006, "Wood and Stone Processing Machinery", "Refers to wood and stone processing machinery."],
            [292007, "Machine Tool Machinery", "Metal cutting machine tools， forging machinery， casting machinery， woodworking machinery， plastics processing machinery， metal materials processing equipment"],
            [292008, "Commercial Machinery", "Refers to the equipment used in commercial and financial activities， including the display cabinet， booth， supermarket shopping cart， shopping basket， marking machine， scanner， binding machine， vending machine， queuing machine， cashier desk， safe box and detector， POS machine， banding machine， etc. used in financial transactions."],
            [292009, "Basic Machinery", "Refers to mechanical parts used to make machinery equipment， mainly including powder metallurgy products， standard fasteners， industrial chains， gear， mold， etc"],
            [292010, "Tools and Accessories", "Refers to pipe fittings， grinding apparatus， abrasive materials， locks， pliers， wrenches， guide rail， tee， electrode holder， welding rod， jacks， hydraulic tools， bearings， transmission parts， springs， fasteners， sealers， pneumatic components， precision parts， jig， steel wire rope， cable， daily tool， general hardware， agricultural artisan as tools， electric pneumatic tools， hardware nylon products， comprehensive measuring tools， hardware tools， etc"],
            [292011, "Food Machinery", "Refers to the production and processing equipment for food， beverage， tobacco and liquor， including rice and noodles machinery， cooking oil machinery， food sterilization equipment， and commercial mobile canteen."],
            [292013, "Cleaning and Ventilation Equipment", "Ventilation and cleaning equipment. Ventilation equipment includes blower， ventilator， industrial fan， air curtain machine， fan accessories， etc. Cleaning equipment includes cleaning machine， industrial laundry equipment， washing machine， sweeper， etc"],
            [292014, "Other Machinery", "Refers to paper and printing machinery， pharmaceutical equipment， footwear machinery， textile machinery， packaging machinery， rocker， welding equipment， glass and rubber equipment."],
            [292101, "Show Tickets and Peripherial Service", "Refers to music， literary and artistic creation， performing arts activities and ticket sales， such as concerts， music festivals， opera， singing and dancing， drama， commic talks， acrobatics， circus， puppet shows， talk show， magic， etc"],
            [292102, "Literature and Art Collectibles", "Refers to the online and offline institutions that sell and appraise collection items such as cultural relics， jewelry， rare stones and ornamental stones， coins， stamps， documents， tickets， trademarks， badges， specimens， ceramics， jade， paintings， etc."],
            [292103, "Stationery， Toys， Gifts", "Specifically refers to the online and offline organizations that produce and sell gifts (such as flowers， gifts， etc.)， stationery and toys"],
            [292104, "Musical Instrument", "Online and offline institutions engaged in production， sales and maintenance of musical instruments. A musical instrument is an instrument that produces musical sounds and recreates music and art."],
            [292105, "Indoor Recreation", "A variety of indoor entertainment， such as KTV， TAKEGISM， electronic entertainment halls， cinemas， strip clubs， casinos， etc"],
            [292106, "Exercise and Fitness", "Online or offline organizations that provide fitness training"],
            [292107, "Sporting Goods", "The enterprises that produce and sell sporting goods， as well as sports protective equipment and sportswear"],
            [292108, "Outdoor Equipments", "Refers to companies that produce and sell outdoor equipment. Outdoor equipment refers to the equipment that needs to be equipped when participating in various adventure tourism and outdoor activities."],
            [292109, "Sports Events & Stadiums", "A sporting event is a formal competition with certain size and grade， such as the World Cup， Olympics， F1， NBA， etc. Stadiums refer to professional places for sports training， sports competitions and mass sports consumption， such as stadiums and gymnasiums (excluding fitness room). Sports trophies， medals and related products are also included in this category"],
            [292110, "Horticulture", "Refers to enterprises that provide products and services for non-productive planting (fruit trees， vegetables， ornamental horticulture， etc.)"],
            [292111, "Lottery & Gambling", "Refers to a company that provides lottery information， online lottery sales， sports betting and entertainment"],
            [292112, "Outdoor Recreation", "Refers to the outdoor recreation and sports activities"],
            [292113, "Others", "Items not included into the categories above."],
            [292114, "Membership Card & Voucher", "Refers to an enterprise that collects membership fees and provides members with other merchants' hotel ticket discounts， restaurant reservation services， private jet yacht reservations， clubs and other life services. The enterprise does not directly provide physical services to users."],
            [292115, "Casino & Gambling", "Places that legally provide gambling as entertainment， and services that legally provide gambling as entertainment"],
            [292116, "Sports and Entertainment E-Commerce", "E-commerce platform for the sale of cultural， sports and entertainment goods to families and individuals"],
            [292117, "Sports and Entertainment Off-Line Retail", "Physical stores selling sports and entertainment products， such as Decathlon. New retail is classified as offline"],
            [292201, "TV Station", "A media organization founded by a state or commercial organization to disseminate video and audio synchronized information"],
            [292202, "Radio Station", "Mass communication organizations that compile， produce and use radio waves to transmit sound programs to audiences in certain areas."],
            [292203, "Movies Studios", "Different kinds of comedies， action， love， fiction movies."],
            [292204, "Audio and Video Production", "Refers to the online and offline organizations (such as tapes， CDS， DVDS， or audio-visual files or products) that publish， distribute and supply service such as film and television， music， animation， variety shows， etc.， including artist studios."],
            [292205, "Online Books & Magazines", "Refers to the online organizations that publish， distribute and serve magazines (including sports magazines)， periodicals， novels， newspapers， papers， comics and other works"],
            [292206, "News", "Including comprehensive web portals (spanning multiple industries and focusing on information dissemination) and new media， but excluding the vertical information platforms of primary and secondary industries"],
            [292207, "Comprehensive Information", "Organization that provide in-depth information and related services in two or more fields (primary and secondary categories)"],
            [292208, "Vertical Information", "Institutions providing all in-depth information and related services in a certain field (first and second level categories of other industries) (such as automobile， living service)"],
            [292209, "Live Video Streaming", "Institutions that provide online video， short video， live streaming， etc"],
            [292210, "Others", "Items not included into the categories above."],
            [292211, "Books & Magazine - Printed Books", "Refers to the offline publication and distribution of magazines (including sports magazines)， periodicals， novels， newspapers， papers， comics， etc.， such as books"],
            [292212, "OTT Vendors", "Over-the-top applications， is an app that delivers video content to your smartphone， tablet， or smart TV using the internet rather than the traditional distribution methods of cable or satellite. Example: Netflix， Amazon Prime"],
            [292301, "Express Service", "Refers to companies that provide point-to-point transportation of goods for individuals or enterprises， including loading and unloading， transportation， warehousing， packaging and handling services， covering road transportation， railway transportation， air transportation， water transportation， etc"],
            [292302, "Freight Forwarding", "A freight forwarder， forwarder， or forwarding agent， is a person or company that organizes shipments for individuals or corporations to get goods from the manufacturer or producer to a market， customer or final point of distribution. A forwarder does not move the goods but acts as an expert in the logistics network."],
            [292303, "Special Goods Transportation", "Transportation activities that require special equipment or special permits other than general goods， including transportation of hazardous chemicals"],
            [292304, "logistics Infrastructure", "Including logistics park， logistics center， distribution center and other infrastructure， and four-way pallet， elevated forklift， automatic sorting machine， automatic guide vehicles (AGV)， containers and other logistics infrastructure equipment"],
            [292305, "Others", "Items not included into the categories above."],
            [292401, "Telecom Operators", "Refers to communications service enterprises related to fixed telephone， mobile phone， television signal， Internet access"],
            [292402, "Virtual Network Operator (VNO)", "Refers to partners that obtain virtual operator license issued by the Ministry of Industry and Information Technology and possess certain kinds of capabilities (such as technical capability， equipment supply capability， market capability， etc.) and form a cooperative relationship with a telecom operator in a certain business or a certain number of businesses"],
            [292403, "TeleCommunication Equipment", "Companies engaged in production， sales， research and development of communication equipment， such as walkie-talkie， radio station， satellite telephone， radio， wired communication equipment， lightning arrester， optical fiber equipment， distributor， communication cable， etc"],
            [292404, "Others", "Items not included into the categories above."],
            [292501, "Banking", "Financial institutions， non-bank financial institutions and policy banks that absorb public deposits established within the territory of the People's Republic of China such as commercial banks， urban credit cooperatives， rural credit cooperatives."],
            [292502, "Securities", "A company whose principal business is equities and other derivatives"],
            [292503, "Insurance", "Refers to companies and their branches that provide insurance business (including consultation)， insurance asset management companies and their branches， insurance brokers， insurance agents or insurance public valuers and other institutions established upon approval of the insurance regulatory body of China; Such as: China Life Insurance， PICC， Ping An Insurance，New China Life Insurance， etc."],
            [292504, "Trust Business", "The trustor entrusts his property right to the trustee based on his trust on the trustee， and the trustee manages or disposes of the property right in the name of the beneficiary or for specific purposes according to the will of the trustor."],
            [292505, "Guarantee and Factoring", "Refers to the companies or organizations that provide guarantee services of loans， financial leasing and other economic contracts for enterprises， or provide guarantee services of consumer credit and other consulting services for individuals"],
            [292506, "Auction & Pawn", "A company that offers auction or pawn services"],
            [292507, "Futures", "Institutions engaged in futures consultation， issuance and transactions."],
            [292508, "Fund", "Fund refers to a certain amount of money set up for a certain purpose， which mainly refers to public offering， private placement and venture capital fund"],
            [292509, "Credit Investigation Service", "It refers to third party which is independent of the credit transaction parties and mainly engaged in credit investigation business. Specialized in the collection， collation， processing and analysis of enterprise and personal credit information， issuing credit reports， providing diversified credit services， helping customers to judge and control credit risks."],
            [292510, "Small-loan Company", "Small loan is a comprehensive consumption loan with individual or enterprise as the core. The amount of loan is generally more than 10，000 yuan and less than 200，000 yuan. Small loan companies in traditional finance generally refer to local small loan companies."],
            [292511, "Others", "Items not included into the categories above."],
            [292512, "Bank Card Organization", "Organizations that do not issue cards directly， provide inter-bank transaction clearing systems， thereby enabling bank cards to be used across banks， regions and borders"],
            [292601, "Comprehensive Financial Management", "Accept the client's entrustment and authorization， and carry out the business activities of investment and asset management in accordance with the investment plan and scheme agreed with the client in advance， generally including a variety of financial products， such as stocks， funds， bonds， etc"],
            [292602, "Online Securities Platform", "Generally， Internet enterprises or other online institutions enter the securities industry through transformation and establish Internet securities platforms"],
            [292603, "Equity Securities(Stock)", "Institutions with qualifications to operate Hong Kong stocks and US stocks"],
            [292604, "Loan Services", "All the services provided by the Internet as a medium， from loan selection， loan issuance to the full recovery of loans."],
            [292605, "Foreign Exchange", "Institutions engaged in foreign exchange trading and foreign exchange speculation"],
            [292606, "Noble Metal", "It refers to the e-commerce trading service platforms that help investors to quote， buy， sell and spot precious metals and other financial derivatives through the third-party institutions."],
            [292607, "P2P", "Companies that provide information release， risk assessment， credit counseling， transaction management， customer service and other intermediary services for the lending activities between borrowers and lenders， through the third-party Internet platform to match the two parties."],
            [292608, "Third Party Payment", "An intermediary platform for funds between buyers and sellers during a transaction， an independent institution that safeguards the interests of both parties in a transaction under the supervision of a bank."],
            [292609, "Crowdfunding", "An organization that provides intermediary services such as information release， project evaluation， transaction management and customer service to promoters and supporters of projects with financing needs;"],
            [292610, "Digital Currency", "Institutions of digital bill trading platforms based on blockchain"],
            [292611, "Financial Web Portals", "A platform providing financial information and financial products， but the platform itself cannot undertake financial products transactions."],
            [292612, "Internet-based Bank", "Mainly refers to banks with Internet banking license issued by CBRC."],
            [292613, "Internet Insurance", "Mainly refers to Internet insurance enterprises with Internet insurance license issued by CIRC."],
            [292614, "Comprehensive Financial Platforms and Tools", "Refers to companies that provide accounting software (including financial tools)， credit card management services and financial information services"],
            [292615, "Others", "Items not included into the categories above."],
            [292701, "Restaurants and Other Eating Places", "Refers to the food and beverage activities， including desserts and pastries， that provide various dishes and staple food， mainly Chinese food and dinner."],
            [292702, "Drinking Places (Alcoholic Beverages)", "Refers to places that provide drinks and cold drinks， including bars"],
            [292703, "Others", "Items not included into the categories above."],
            [292801, "Software Tools", "Mainly used in business scenes， utility software (such as financial software， database software， graphics software， development software， office software， etc.) that are closely related to work."],
            [292802, "Multimedia Processing", "Utility software that make or process pictures， audio， video and other multimedia files."],
            [292803, "Social Messaging", "Software for instant messaging， online social networking (not including social networking for dating purposes)"],
            [292804, "Utility Tools", "Utility software developed for individuals to meet daily life needs (excluding O2O and e-commerce) ， such as browser， calendar， weather service， anti-virus software， dictionary， etc."],
            [292805, "Others", "Items not included into the categories above."],
            [292901, "Medicine Manufacturing", "Manufacture， sell durgs that aim for treatment， like Pfizer"],
            [292902, "Health and Wellness Products", "Manufacture， sell health products， like Durex"],
            [292903, "Veterinary Medicine", "Manufacture， sell Veterinary Medicine"],
            [292904, "Pharmaceutical Retail", "Companies that only do business in durg retail， like CVS and Walgreens."],
            [292905, "Other Drugs", "Companies not included into the categories above."],
            [293001, "Commercial Constructions", "This industry group comprises establishments primarily responsible for the construction (including new work， additions， alterations， maintenance， and repairs) of nonresidential buildings."],
            [293002, "Residential Constructions", "This industry comprises establishments primarily responsible for the construction or remodeling and renovation of single-family and multifamily residential buildings."],
            [293003, "Civil Constructions", "This industry comprises establishments primarily engaged in heavy and civil engineering construction projects， like parks， gardens， statues， etc."],
            [293004, "Road Construction", "This industry comprises establishments primarily engaged in the construction of highways (including elevated)， streets， roads， airport runways， public sidewalks， or bridges."],
            [293005, "Other Constructions", "Companies not included into the categories above."],
            [293101, "Merchants Joint Exhibition Platform", "Comprehensive investment promotion information platforms involving more than two categories， such as 28 and 78 Business Opportunities Network"],
            [293102, "Daily Products Franchisee", "Including personal consumer goods (excluding alcohol) joining sales， household appliances joining， etc.， including pet products joining， personal washing products， adult products joining， electrical appliances joining， etc."],
            [293103, "Daily Service Franchisee", "Merchants join the service category， including life services (excluding leisure and entertainment)， such as: dry cleaning joining， home economics joining， sister-in-law joining， vision correction joining， nursing service joining， Yuezi center joining and so on."],
            [293104, "Clothing Accessories Franchisee", "Investment promotion and alliance clothing， shoes and hats， luggage and accessories mainly refer to clothing， shoes and hats used in daily life， mainly in offline/online stores， such as children's clothing， women's clothing/underwear， cloth shoes， etc."],
            [293105, "Beauty Salons Franchisee", "Merchants join the beauty category， such as: beauty salon joining， health club， men's spa joining， postpartum repair joining and so on."],
            [293106, "Indoor Entertainment Franchisee", "Refers to indoor entertainment， such as KTV， Chamber of Secrets， indoor amusement parks， electronic amusement halls， cinemas， VR， gym joining and other entertainment places."],
            [293107, "Education and Training Franchisee", "Merchants join education and training categories， such as schools， vocational education， pre-job training， etc.， mainly educational joining， supplemented by training， such as early education joining， vocational education joining， and so on."],
            [293108, "Hotel Fanchisee", "Merchants join hotels， such as theme hotels."],
            [293109, "Restaurant Franchisee", "Investment promotion to join catering， etc. Catering mainly includes food and drink items， mainly for offline store catering， such as hot pot/dessert/barbecue， etc."],
            [293110, "Medicine Franchisee", "Specially refers to medical and pharmaceutical investment promotion."],
            [293111, "Real Estate， Home Building， and Materials Franchisee", "Promot the investment Franchisee in terms of real estate， house and home， building materials."],
            [293112, "Food Franchisee", "Refers to merchants to join food (excluding alcohol)， etc."],
            [293113, "Industrial Franchisee", "Refers to industrial joining"],
            [293114, "Automotive Products Franchisee", "Refers to the joining of automobile products， mainly refers to the joining of automobile service products such as automobile beauty， automobile maintenance， automobile decoration， automobile cleaning and so on."],
            [293115, "Internet Software Franchisee", "Refers to investment promotion related to Internet technology and software."],
            [293116, "Recruitment Agency Franchisee", "Refers to merchants that provide recruitment intermediary services， generally do not provide systematic vocational training"],
            [293117, "Others", "Merchants that are not included in the above secondary categories"],
            [293118, "Weight Losing Francisee", "A weight-loss agency， such as a weight-loss center."],
            [293119, "Drinks & Baking Franchisee", "It is mainly drinks， including derivatives of drinks (such as milk tea， coffee， ice cream， sweet shops， bakeries， bakeries， bakeries， cake shops)."],
            [293120, "Health Products Franchisee", "Refers to health products joining"],
            [293121, "Alcohol Franchisee", "Refers to alcohol joining"],
            [293122, "Agricultural Franchisee", "Refers to agricultural joining"],
            [293123, "Business Services Franchisee", "Refers to business service joining"],
        ];
    }
}
